---
title: "Stats in R Assignment"
author: "Alex Lucchesi"
date: "2023/05/30"
output: html_document
---

## Assignment

For today's assignment, you will be given a blank notebook and a link to the [Call of Duty Dataset](https://www.kaggle.com/datasets/beridzeg45/call-of-duty-reviews) You will need to fill out the notebook and create your own code chunks to run code. Remember that we use this code without any quotation marks to create a code chunk: '`{r} '` \### Your Goal:

To receive credit for today's assignment, you will need to:

-   Import the dataset
-   Load the dataset into a tibble
-   Mutate a new column
-   Create a hypothesis regarding your data and communicate that hypothesis in a scientific method.
-   Create a notebook that has markdown cells, explaining your code and process/thoughts. **Your markdown should be well thought out and reflect a thorough analysis.**
-   Clean the data
-   Explore the data (include visualizations)
-   Create a statistical test and communicate the results

```{r}

```
